### ISSUE TITLE
Download model_zoo.zip problem

### ISSUE THREAD

**Issue by lizhenstat** [ofsoundof/group_sparsity#2]
Hi, thanks for your work and sharing of the code!
However, I have a problem downloading the pretrained models
(1) I tried to use VPN to directly download the model_zoo.zip but filed (Which I can download other google drive file successfully.)
(2) I follow [this tutorial](https://medium.com/@acpanjan/download-google-drive-files-using-wget-3c2c025a8b99) and use wget to download the model, but still not working.
Can you share the directory of the file? Since I saw the download link 
"...view?usp=sharing" flash for one second and disappear and redirect to "...view"

Thanks for your time and looking forward to your reply.

**Comment by lizhenstat** [comment]
Sorry to disturb, I use the IE browser instead of chrome, and it finally works!

**Comment by ofsoundof** [comment]
I'm glad that you solved the problem.
